<?php $this->plugin('cmstranslate')->setTranslatorTextDomain('playgroundcms'); ?>
<div class="col-md-12">
    <h2> <?php echo $this->cmsTranslate('Comments'); ?></h2>
    <?php if(count($this->commentsPaginator) > 0) : ?>
        <?php foreach ($this->commentsPaginator as $comment) : ?>
            <div class="col-md-12">
                <div class="author pull-right">
                    <div class="icon">
                        <img src="<?php echo "http://www.gravatar.com/avatar/".md5(strtolower(trim($comment->getEmail())));?>" class="img-circle" alt="">
                    </div> 
                </div>
                <div class="comment on-left">
                    <div class="sender"><?php echo $comment->getName(); ?> (<?php echo $comment->getEmail(); ?>)</div>
                     <div class="time small muted">
                        <?php echo $comment->getUpdatedAt()->format('d/m/Y H:i:s'); ?>
                    </div>
                    <div class="text">
                        <?php echo $comment->getComment(); ?>
                    </div>
                </div>
            </div>
            <div class="clearfix">&nbsp;</div>
            <hr />
        <?php endforeach; ?>
        <?php $paginator =  $this->paginationControl($this->commentsPaginator , 'Sliding', 'playground-cms/partial/pagination.phtml', array('uri' => $this->uri, "countResults" => $this->nbComments)); ?> 
        <?php if(strlen($paginator) > 10) :?>
                <div class="divider"></div>
                <?php echo $paginator; ?>
        <?php endif; ?>
    <?php else : ?>
        <div class="bs-callout bs-callout-danger">
            <h4>
                <?php echo $this->cmsTranslate('No comment'); ?> 
            </h4>
        </div>
    <?php endif; ?>
    <div>
        <?php if(!empty($return) && $return['status'] != 0) : ?>
            <div class="row">
                <div class="alert alert-danger">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h4><i class="fa fa-ban"></i> <strong><?php echo $return['message'];?>!</strong></h4>
                </div>
            </div>
        <?php endif; ?>

        <form role="form" method="post">
            <input type="hidden" class="form-control" name="comment[articleId]" value="<?php echo $this->article->getId()?>">
            <input type="hidden" class="form-control" name="comment[locale]" value="<?php echo $this->ressource->getLocale()?>">

            <div class="form-group">
                <label for="email">Email</label>
                <input type="email" class="form-control" name="comment[email]" id="email" placeholder="Email" value="<?php echo @$data['comment']['email'] ?>" required>
            </div>
            <div class="form-group">
                <label for="name">Name</label>
                <input type="text" class="form-control" name="comment[name]" id="name" placeholder="Author" required value="<?php echo @$data['comment']['name'] ?>" >
            </div>
            <div class="form-group">
                <label for="comment">Comment</label>
                <textarea id="comment" name="comment[comment]"  class="form-control" rows="4" required><?php echo @$data['comment']['comment'] ?></textarea>
            </div>
            <button type="submit" class="btn btn-success pull-right">Submit</button>
            </form>
        </div>
</div>
<div class="clearfix">&nbsp;</div>
<div class="clearfix">&nbsp;</div>
<div class="clearfix">&nbsp;</div>


