<?php 
$nbResults = count($this->blocks) + count($this->layouts) + count($this->menus) + count($this->pages) + count($this->templates) + count($this->zones) + count($this->articles) + count($this->categories) + count($this->polls) + count($this->tags); 
?>
<div class="row">
    <div class="col-md-12">
        <section class="widget">
            <ol class="breadcrumb">
                <li><a href="<?php echo $this->url('admin'); ?>"><i class="fa fa-dashboard"></i> Dashboard</a></li>
                <li class="active">Search : <?php echo $this->search ?> </li>
            </ol>
        </section>
    </div>
</div>

<section class="widget">
    <header>
        <h4>
            <i class="fa fa-search"></i>
            Result of the search : <?php echo $this->search ?>  (<?php echo $nbResults;?>)
        </h4>
    </header>
    <div class="clearfix">&nbsp;</div>
    <div class="body">
        <div class="" style="position: relative; overflow: hidden; width: auto; height: auto;"><div id="feed" class="feed" style="overflow: hidden; width: auto; height: auto;">
            <div class="wrapper">
                <div class="vertical-line"></div>
                <section class="widget widget-tabs large">
                    <header>
                        <ul class="nav nav-tabs">
                            <li class="active">
                                <a href="#blocks" data-toggle="tab">Blocks (<?php echo count($this->blocks); ?>)</a>
                            </li>
                            <li class="">
                                <a href="#layouts" data-toggle="tab">Layouts (<?php echo count($this->layouts); ?>)</a>
                            </li>
                            <li class="">
                                <a href="#menus" data-toggle="tab">Menus (<?php echo count($this->menus); ?>)</a>
                            </li>
                            <li class="">
                                <a href="#pages" data-toggle="tab">Pages (<?php echo count($this->pages); ?>)</a>
                            </li>
                            <li class="">
                                <a href="#templates" data-toggle="tab">Templates (<?php echo count($this->templates); ?>)</a>
                            </li>
                            <li class="">
                                <a href="#zones" data-toggle="tab">Zones (<?php echo count($this->zones); ?>)</a>
                            </li>
                            <li class="">
                                <a href="#articles" data-toggle="tab">Articles (<?php echo count($this->articles); ?>)</a>
                            </li>
                            <li class="">
                                <a href="#categories" data-toggle="tab">Categories (<?php echo count($this->categories); ?>)</a>
                            </li>
                            <li class="">
                                <a href="#polls" data-toggle="tab">Polls (<?php echo count($this->polls); ?>)</a>
                            </li>
                            <li class="">
                                <a href="#tags" data-toggle="tab">Tags (<?php echo count($this->tags); ?>)</a>
                            </li>
                        </ul>
                    </header>
                    <div class="body tab-content">
                        <div id="blocks" class="tab-pane clearfix active">
                            <h5 class="tab-header"><i class="fa fa-code"></i> Blocks</h5>
                            <ul class="news-list">
                                <?php if(count($this->blocks) > 0): ?>
                                    <?php foreach ($this->blocks as $block) : ?>
                                        <li>
                                            <div class="icon pull-left">
                                                <i class="fa fa-code"></i>
                                            </div>
                                            <div class="news-item-info">
                                                <div class="name"><a href="<?php echo $this->url('admin/playgroundcmsadmin/block_edit', array('id' => $block->getId())) ?>"><?php echo $block->getName(); ?></a></div>
                                                <div class="comment">
                                                    <?php echo $block->getType(); ?>
                                                </div>
                                                <div class="time pull-left">
                                                    Created at <?php echo $block->getCreatedAt()->format('d M Y, H:i'); ?>
                                                </div>
                                            </div>
                                        </li>
                                    <?php endforeach; ?>
                                <?php endif; ?>
                            </ul>
                        </div>
                        <div id="layouts" class="tab-pane">
                            <h5 class="tab-header"><i class="fa fa-windows"></i> Layouts</h5>
                            <ul class="news-list">
                                <?php if(count($this->layouts) > 0): ?>
                                    <?php foreach ($this->layouts as $layout) : ?>
                                        <li>
                                            <div class="icon pull-left">
                                                <i class="fa fa-windows"></i>
                                            </div>
                                            <div class="news-item-info">
                                                <div class="name"><a href="<?php echo $this->url('admin/playgroundcmsadmin/layout_edit', array('id' => $layout->getId())) ?>"><?php echo $layout->getName(); ?></a></div>
                                                <div class="comment">
                                                    <?php echo $layout->getFile(); ?>
                                                </div>
                                                <div class="time pull-left">
                                                    Created at <?php echo $layout->getCreatedAt()->format('d M Y, H:i'); ?>
                                                </div>
                                            </div>
                                        </li>
                                    <?php endforeach; ?>  
                                <?php endif; ?>  
                            </ul>
                        </div>
                        <div id="menus" class="tab-pane">
                            <h5 class="tab-header"><i class="fa fa-tree"></i> Menus</h5>
                            <ul class="news-list">
                                <?php if(count($this->menus) > 0): ?>
                                    <?php foreach ($this->menus as $menu) : ?>
                                        <li>
                                            <div class="icon pull-left">
                                                <?php $status = 'color-green'; ?>
                                                <?php if ($menu->getStatus() == 0) :?>
                                                    <?php $status = 'color-red'; ?>
                                                <?php endif; ?>
                                                <i class="fa fa-tree <?php echo $status; ?>"></i>
                                            </div>
                                            <div class="news-item-info">
                                                <div class="name"><a href="<?php echo $this->url('admin/playgroundcmsadmin/menu_edit', array('id' => $menu->getId())) ?>"><?php echo $menu->getTitle(); ?></a></div>
                                                <div class="comment">
                                                    <?php echo $menu->getUrl(); ?>
                                                </div>
                                                <div class="time pull-left">
                                                    Created at <?php echo $menu->getCreatedAt()->format('d M Y, H:i'); ?>
                                                </div>
                                            </div>
                                        </li>
                                    <?php endforeach; ?>
                                <?php endif; ?> 
                            </ul>
                        </div>
                        <div id="pages" class="tab-pane">
                            <h5 class="tab-header"><i class="fa fa-desktop"></i> Pages</h5>
                            <ul class="news-list">
                                <?php if(count($this->pages) > 0): ?>
                                    <?php foreach ($this->pages as $page) : ?>
                                        <?php $ressource = $page["ressource"]; ?>
                                        <?php $page = $page["page"]; ?>
                                        <li>
                                            <div class="icon pull-left">
                                                <?php $status = 'color-green'; ?>
                                                <?php if ($page->getStatus() == 0) :?>
                                                    <?php $status = 'color-red'; ?>
                                                <?php endif; ?>
                                                <i class="fa fa-desktop <?php echo $status; ?>"></i>
                                            </div>
                                            <div class="news-item-info">
                                                <div class="name"><a href="<?php echo $this->url('admin/playgroundcmsadmin/page_edit', array('id' => $page->getId())) ?>"><?php echo $page->getTitle(); ?></a></div>
                                                <div class="comment">
                                                    <?php echo $ressource->getUrl(); ?>
                                                </div>
                                                <div class="time pull-left">
                                                    Created at <?php echo $page->getCreatedAt()->format('d M Y, H:i'); ?>
                                                </div>
                                            </div>
                                        </li>
                                    <?php endforeach; ?> 
                                <?php endif; ?>
                            </ul>
                        </div>
                        <div id="templates" class="tab-pane">
                            <h5 class="tab-header"><i class="fa fa-align-justify"></i> Templates</h5>
                            <ul class="news-list">
                                <?php foreach ($this->templates as $template) : ?>
                                <li>
                                    <div class="icon pull-left">
                                        <i class="fa fa-align-justify"></i>
                                    </div>
                                    <div class="news-item-info">
                                        <div class="name"><a href="<?php echo $this->url('admin/playgroundcmsadmin/template_edit', array('id' => $template->getId())) ?>"><?php echo $template->getName(); ?></a></div>
                                        <div class="comment">
                                            <?php echo $template->getFile(); ?>
                                        </div>
                                        <div class="time pull-left">
                                            Created at <?php echo $template->getCreatedAt()->format('d M Y, H:i'); ?>
                                        </div>
                                    </div>
                                </li>
                                <?php endforeach; ?>    
                            </ul>
                        </div>
                        <div id="zones" class="tab-pane">
                            <h5 class="tab-header"><i class="fa fa-th-large"></i> Zones</h5>
                            <ul class="news-list">
                                <?php foreach ($this->zones as $zone) : ?>
                                <li>
                                    <div class="icon pull-left">
                                        <i class="fa fa-th-large"></i>
                                    </div>
                                    <div class="news-item-info">
                                        <div class="name"><a href="<?php echo $this->url('admin/playgroundcmsadmin/zone')?>"><?php echo $zone->getName(); ?></a></div>
                                        <div class="comment">
                                            <?php if(!empty($this->layoutsPerZone[$zone->getId()])) : ?>
                                                <?php echo count($this->layoutsPerZone[$zone->getId()]); ?> layouts associated
                                            <?php else : ?>
                                                0 layout associated
                                            <?php endif; ?>
                                        </div>
                                        <div class="time pull-left">
                                            Created at <?php echo $zone->getCreatedAt()->format('d M Y, H:i'); ?>
                                        </div>
                                    </div>
                                </li>
                                <?php endforeach; ?>  
                            </ul>
                        </div>
                        <div id="articles" class="tab-pane">
                            <h5 class="tab-header"><i class="fa fa-edit"></i> Articles</h5>
                            <ul class="news-list">
                                <?php foreach ($this->articles as $article) : ?>
                                    <?php $ressource = $article["ressource"]; ?>
                                    <?php $article = $article["article"]; ?>
                                    <li>
                                        <div class="icon pull-left">
                                            <?php $status = 'color-green'; ?>
                                            <?php if ($article->getStatus() == 0) :?>
                                                <?php $status = 'color-red'; ?>
                                            <?php endif; ?>
                                            <i class="fa fa-edit <?php echo $status; ?>"></i>
                                        </div>
                                        <div class="news-item-info">
                                            <div class="name"><a href="<?php echo $this->url('admin/playgroundpublishingadmin/article_edit', array('id' => $article->getId())) ?>"><?php echo $article->getTitle(); ?></a></div>
                                            <div class="comment">
                                                <?php echo $ressource->getUrl(); ?>
                                            </div>
                                            <div class="time pull-left">
                                                Created at <?php echo $article->getCreatedAt()->format('d M Y, H:i'); ?>
                                            </div>
                                        </div>
                                    </li>
                                <?php endforeach; ?>
                            </ul>
                        </div>
                        <div id="categories" class="tab-pane">
                            <h5 class="tab-header"><i class="fa fa-book"></i> Categories</h5>
                            <ul class="news-list">
                                <?php foreach ($this->categories as $category) : ?>
                                    <?php $ressource = $category["ressource"]; ?>
                                    <?php $category = $category["category"]; ?>
                                    <li>
                                        <div class="icon pull-left">
                                            <?php $status = 'color-green'; ?>
                                            <?php if ($category->getStatus() == 0) :?>
                                                <?php $status = 'color-red'; ?>
                                            <?php endif; ?>
                                            <i class="fa fa-book <?php echo $status; ?>"></i>
                                        </div>
                                        <div class="news-item-info">
                                            <div class="name"><a href="<?php echo $this->url('admin/playgroundpublishingadmin/category_edit', array('id' => $category->getId())) ?>"><?php echo $category->getTitle(); ?></a></div>
                                            <div class="comment">
                                                <?php echo $ressource->getUrl(); ?>
                                            </div>
                                            <div class="time pull-left">
                                                Created at <?php echo $category->getCreatedAt()->format('d M Y, H:i'); ?>
                                            </div>
                                        </div>
                                    </li>
                                <?php endforeach; ?>
                             </ul>
                        </div>
                        <div id="polls" class="tab-pane">
                            <h5 class="tab-header"><i class="fa fa-question"></i> Polls</h5>
                            <ul class="news-list">
                                <?php foreach ($this->polls as $poll) : ?>
                                <?php $ressource = $poll["ressource"]; ?>
                                <?php $poll = $poll["poll"]; ?>
                                <li>
                                    <div class="icon pull-left">
                                        <?php $status = 'color-green'; ?>
                                        <?php if ($poll->getStatus() == 0) :?>
                                            <?php $status = 'color-red'; ?>
                                        <?php endif; ?>
                                        <i class="fa fa-question <?php echo $status; ?>"></i>
                                    </div>
                                    <div class="news-item-info">
                                        <div class="name"><a href="<?php echo $this->url('admin/playgroundpublishingadmin/poll_edit', array('id' => $poll->getId())) ?>"><?php echo $poll->getTitle(); ?></a></div>
                                        <div class="comment">
                                            <?php echo $ressource->getUrl(); ?>
                                        </div>
                                        <div class="time pull-left">
                                            Created at <?php echo $poll->getCreatedAt()->format('d M Y, H:i'); ?>
                                        </div>
                                    </div>
                                </li>
                            <?php endforeach; ?>
                            </ul>
                        </div>
                        <div id="tags" class="tab-pane">
                            <h5 class="tab-header"><i class="fa fa-tag"></i> Tags</h5>
                            <ul class="news-list">
                                 <?php foreach ($this->tags as $tag) : ?>
                                <?php $ressource = $tag["ressource"]; ?>
                                <?php $tag = $tag["tag"]; ?>
                                <li>
                                    <div class="icon pull-left">
                                        <?php $status = 'color-green'; ?>
                                        <?php if ($tag->getStatus() == 0) :?>
                                            <?php $status = 'color-red'; ?>
                                        <?php endif; ?>
                                        <i class="fa fa-tag <?php echo $status; ?>"></i>
                                    </div>
                                    <div class="news-item-info">
                                        <div class="name"><a href="<?php echo $this->url('admin/playgroundpublishingadmin/tag_edit', array('id' => $tag->getId())) ?>"><?php echo $tag->getTitle(); ?></a></div>
                                        <div class="comment">
                                            <?php echo $ressource->getUrl(); ?>
                                        </div>
                                        <div class="time pull-left">
                                            Created at <?php echo $tag->getCreatedAt()->format('d M Y, H:i'); ?>
                                        </div>
                                    </div>
                                </li>
                            <?php endforeach; ?>
                            </ul>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </div>
    <div class="clearfix">&nbsp;</div>
</section>

<div id="searchHightlight" class="hide"><?php echo $this->search ?></div>